#!/usr/bin/env bun
// Emit the stylesheet as a TypeScript module.
//
// The custom element renders into a shadow root, and a shadow root cannot see the
// host page's CSS — so it has to carry its own copy. "One script tag" only means one
// script tag if the styles come with it.
//
// Generated rather than imported because the bundler treats a `.css` import as a
// stylesheet to extract, not as text, and fighting that produces a build that works
// by accident. Same shape as generate-json-schema.ts: one source of truth, a
// generated artifact, and a `--check` mode so CI notices when they drift.
//
// Usage: bun scripts/generate-style-module.ts [--check]

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';

const REPO_ROOT = resolve(import.meta.dir, '..');
const SOURCE = join(REPO_ROOT, 'src/styles/clotho.css');
const OUT_FILE = join(REPO_ROOT, 'src/styles/inline.ts');

const CHECK_ONLY = process.argv.includes('--check');

const css = readFileSync(SOURCE, 'utf-8');

const module = `// GENERATED by scripts/generate-style-module.ts — do not edit.
//
// The stylesheet as a string, for the custom element's shadow root. Run
// \`bun run styles:generate\` after changing src/styles/clotho.css.

export const CLOTHO_STYLES = ${JSON.stringify(css)};
`;

if (CHECK_ONLY) {
  const current = existsSync(OUT_FILE) ? readFileSync(OUT_FILE, 'utf-8') : '';
  if (current !== module) {
    console.error('inline stylesheet is out of date with src/styles/clotho.css.');
    console.error('Run: bun run styles:generate');
    process.exit(1);
  }
  console.log('inline stylesheet check OK — in sync with the stylesheet.');
  process.exit(0);
}

writeFileSync(OUT_FILE, module, 'utf-8');
console.log(`wrote ${OUT_FILE} (${(css.length / 1024).toFixed(1)}KB of CSS)`);
